config/routes.rb
Rails.application.routes.draw do

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">

          <%= render "shared/application_nav" %>

          <%= yield %>

          <%= render "shared/application_footer" %>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>

<p><%= number_to_phone "5555555555" %></p>

<p><%= number_to_currency "18450" %></p>

<p><%= number_with_delimiter "15087263847623" %></p>

app/views/pages/home.html.erb
<div class="inner cover">
  <h1 class="cover-heading">Cover your page.</h1>
  <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
  <p class="lead">
    <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
  </p>
</div>

<div class="mastfoot">
  <div class="inner">
    <p>Cover template for <a href="https://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  </div>
</div>

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p>Footer</p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Rebecca Buie</h3>
    <nav class="nav nav-masthead">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About Me", about_me_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
</div>